### ISSUE TITLE
example does not demonstrate refresh

### ISSUE THREAD

**Issue by scott2b** [FusionAuth/fusionauth-example-python-flask#3]
It is not clear from this example how one would build a workflow which refreshes without requiring the user to re-authenticate. The example as-is seems to limit the authorization to the time specified for access tokens, not refresh tokens.

According to the documentation, an application that is configured to generate refresh tokens should do so. It seems, however, that a refresh token is only provided if the offline_access scope is specified. The `exchange_o_auth_code_for_access_token_using_pkce` client method however does not provide a mechanism for specifying the scope, thus the token returned is just an access token with no refresh token, and for the given workflow there is no clear path to refreshing the user's authorization in the event of access token timeout.

This is more of a question than an issue. Is there a standard approach that should be taken for a refresh enabled workflow? It is not clear from this flask example.

**Comment by scott2b** [comment]
I have tried subclassing `FusionAuthClient` and overriding `exchange_o_auth_code_for_access_token_using_pkce` to explicitly pass in the `offline_access` scope (I also tried `offline-access` for good measure). The response is the same -- it only contains an access token.

I have checked my application configuration to verify that "Generate refresh tokens" is enabled, and "Refresh token" is an enabled grant.

**Comment by scott2b** [comment]
Ok, I see now that `scope=offline_access` needs to be specified in the original request to the `/oauth2/authorize` endpoint. I am now getting the refresh token along with the access token. Closing this.

**Comment by mooreds** [comment]
@scott2b Thanks! Sorry if this was unclear.

I'd happily accept a PR with this functionality, because a refresh_token is a pretty common thing.

**Comment by scott2b** [comment]
Ok. Been working on this. It all turns out to be rather non-trivial because refresh really only makes sense if you are keeping track of some kind of authentication, such as in a session.

I had to do a lot of wrestling with some of FusionAuth's quirks, which include the inability to invalidate access tokens, and a persistent sort of tendency to re-generate user registrations and even entire users that have been deleted if the user subsequently makes various requests.

I think I have something that is working, but am hesitant to actually submit it as a PR because it is so much change and seems like it should be a distinct example. I'll let you take a look and let me know how to proceed. Please let me know if you think there are better approaches to some of these security issues spelled out.

https://github.com/scott2b/fusionauth-example-python-flask/tree/session_with_refresh
